AWSTemplateFormatVersion: '2010-09-09'

Transform:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/function-refs-in-policy-attributes.html
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31


Description: >
  SAM Template for elastic event store

Metadata:
  AWS::ServerlessRepo::Application:
    Name: elastic-event-store
    Description: Elastic Event Store on top of DynamoDB
    Author: Reda Laanait
    SpdxLicenseId: MIT
    LicenseUrl: ../../LICENSE.txt
    ReadmeUrl: ../../README.md
    Labels: ['event-store', 'event-sourcing', 'ddd', 'dynamodb', 'serverless', 'go']
    HomePageUrl: https://github.com/ln80/event-store
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/ln80/event-store

Parameters:
  Name:
    Type: String
    MinLength: '3'
    Description: |
      Serverless application name mainly used as prefix for its under resource names.

  DynamoDBBillingMode:
    Type: String
    Default: PAY_PER_REQUEST
    AllowedValues:
      - PROVISIONED
      - PAY_PER_REQUEST
  
  DynamoDBReadCapacity:
    Type: Number
    Default: 0
  
  DynamoDBWriteCapacity:
    Type: Number
    Default: 0
  
  AlarmSNSTopicArn:
    Type: String
    Default: ""
    Description: |
      AlarmSNSTopicArn receives alarms when indexing and forwarding lambdas are facing issues.

  PublishSNSTopicArn:
    Type: String
    Default: ""
    Description: |
      SNS topic ARN to forward events to.

  BatchRecordEnabled:
    Type: String
    Default: "false"
    AllowedValues:
      - "false"
      - "true"
    Description: |
      BatchRecordEnabled indicates wether or not record events have to be published in a single message or as batch.

  EncodingFormat:
    Type: String
    Default: "JSON"
    AllowedValues:
      - "JSON"
      - "AVRO"
    Description: |
      EncodingFormat of events. It should be changed. Otherwise this might create some inconsistencies.

  AvroGlueSchemaRegistryName:
    Type: String
    Default: ""
    Description: |
      AvroGlueSchemaRegistryName is the name of schema registry used by AVRO Event Serializer. 
      It's Mainly used by forwarder to add global stream sequence to events before forwarding.
  
  RetainResource:
    Type: String
    Default: "false"
    AllowedValues:
      - "false"
      - "true"
    Description: |
      RetainResource indicates if the Event Store table is subject to deletion or not.

  Tracing:
    Type: String
    Default: "Disabled"
    AllowedValues:
      - "Disabled"
      - "Active"
    Description: |
      Tracing enable or disable x-ray tracing for Lambda functions.

  VerbosityLevel: 
    Type: Number
    Default: 1
    Description: |
      VerbosityLevel number define the max log verbosity level, e.g, '0' for Info only, '1' to include debug

Conditions:
  MustEnableAlarm: !Not
    - !Equals
      - !Ref AlarmSNSTopicArn
      - ''
  MustForward:
    !Not
      - !Equals
        - ''
        - !Ref PublishSNSTopicArn
  MustRetainResource:
    !Equals
      - !Ref RetainResource
      - "true"
  MustUseAvro:
    !Equals
      - !Ref EncodingFormat
      - "AVRO"

Globals:
  Function:
    Timeout: 5
    Runtime: provided.al2
    Handler: bootstrap
    Architectures: [ arm64 ]
    Tracing: !Ref Tracing
    ReservedConcurrentExecutions: 10
    Environment:
      Variables:
        VERBOSITY_LEVEL: !Ref VerbosityLevel
        ENCODING_FORMAT: !Sub 
                - "{{resolve:ssm:${ParameterName}}}"
                - { ParameterName: !Ref EncodingFormatParameter }
        AVRO_GLUE_SCHEMA_REGISTRY: !Ref AvroGlueSchemaRegistryName

Resources:
  EncodingFormatParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Name}/event-encoding-format
      Type: String
      Value: !Ref EncodingFormat
      Description: Events encoding format. It should not be updated after stack creation
      AllowedPattern: "^[a-zA-Z]{1,10}$"
        
  EventTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: !If
      - "MustRetainResource"
      - "RetainExceptOnCreate" 
      - "Delete"
    Properties:
        DeletionProtectionEnabled: !If
          - "MustRetainResource"
          - true
          - false
        TableName: !Sub ${Name}-table
        AttributeDefinitions:
          -
            AttributeName: _pk
            AttributeType: S
          -
            AttributeName: _sk
            AttributeType: S
          -
            AttributeName: _lsik
            AttributeType: S
        KeySchema:
          -
            AttributeName: _pk
            KeyType: HASH
          -
            AttributeName: _sk
            KeyType: RANGE
        LocalSecondaryIndexes:
          - 
            IndexName: _lsi
            KeySchema:
              - 
                AttributeName: _pk
                KeyType: HASH
              - 
                AttributeName: _lsik
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
        TimeToLiveSpecification:
            AttributeName: _ttl
            Enabled: true
        BillingMode: !Ref DynamoDBBillingMode
        ProvisionedThroughput:
          ReadCapacityUnits: !Ref DynamoDBReadCapacity
          WriteCapacityUnits: !Ref DynamoDBWriteCapacity
        StreamSpecification:
          StreamViewType: NEW_IMAGE

  IndexerDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
        QueueName: !Sub ${Name}-indexer-dlq
        MessageRetentionPeriod: 1209600 # 14 days
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 180

  ForwarderDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
        QueueName: !Sub ${Name}-forwarder-dlq
        MessageRetentionPeriod: 1209600 # 14 days
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 180

  # LAMBDA FUNCTIONS:
  
  IndexerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub ${Name}-Indexer
      CodeUri: indexer/
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt EventTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1 # much safer
            BisectBatchOnFunctionError: false
            ParallelizationFactor: 1
            MaximumRetryAttempts: 1000
            DestinationConfig:
              OnFailure:
                Type: SQS
                Destination: !GetAtt IndexerDeadLetterQueue.Arn
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"], "dynamodb": { "Keys" : {"_pk": {"S": [{"anything-but": [ "internal" ]}]}}}}'
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt IndexerDeadLetterQueue.QueueName
      Environment:
          Variables:
            DYNAMODB_TABLE: !Ref EventTable

  IndexerCloudWatchAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: MustEnableAlarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub 'Indexing a global stream is facing issues'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub ${Name}-Indexer
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 30
      Statistic: Sum
      Threshold: 1
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  ForwarderFunction:
      Type: AWS::Serverless::Function
      Condition: MustForward
      Metadata:
        BuildMethod: go1.x
      Properties:
        FunctionName: !Sub ${Name}-Forwarder
        CodeUri: forwarder/
        Events:
          StreamEvent:
            Type: DynamoDB
            Properties:
              Stream: !GetAtt EventTable.StreamArn
              StartingPosition: TRIM_HORIZON
              BatchSize: 1
              BisectBatchOnFunctionError: false
              ParallelizationFactor: 1
              # MaximumRecordAgeInSeconds: -1
              # MaximumRetryAttempts: -1
              MaximumRetryAttempts: 1000
              DestinationConfig:
                OnFailure:
                  Destination: !GetAtt ForwarderDeadLetterQueue.Arn
              FilterCriteria:
                Filters:
                  - Pattern: '{"eventName": ["MODIFY"], "dynamodb": { "Keys" : {"_pk": {"S": [{"anything-but": [ "internal" ]}]}}}}'
        Policies:
          - AWSLambdaDynamoDBExecutionRole
          - SQSSendMessagePolicy:
              QueueName: !GetAtt ForwarderDeadLetterQueue.QueueName
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'sns:Publish'
                Resource: !Ref PublishSNSTopicArn
          - !If
            - MustUseAvro
            - AWSGlueSchemaRegistryReadonlyAccess
            - !Ref AWS::NoValue
        Environment:
            Variables:
              SNS_TOPIC: !Ref PublishSNSTopicArn
              BATCH_RECORD_ENABLED: !Ref BatchRecordEnabled

  ForwarderCloudWatchAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: MustEnableAlarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub 'Forwarding events to SNS topic is facing issues'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub ${Name}-Forwarder
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 30
      Statistic: Sum
      Threshold: 1
      AlarmActions:
        - !Ref AlarmSNSTopicArn

Outputs:
  EventTable:
    Description: "Dynamodb Event Table"
    Value: !Ref EventTable
