name: Linter
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [".", "tool"]
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ${{ matrix.directory }}/go.mod
          cache-dependency-path: ${{ matrix.directory }}/go.sum

      - name: Run Linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
          args: --enable=misspell
          working-directory: ${{ matrix.directory }}
