name: Linter
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [".", "stack/elastic"]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.x'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          # version: "1.21"
          args: --enable misspell
          working-directory: ${{ matrix.directory }}