name: Security Checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Run Gosec scanner
        uses: securego/gosec@master
        with:
          args: -exclude-dir=eventtest ./...